

export default function CartPage(){
    return(
    <div className="no-scrollbar">
        <h1>Cart Page</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis aliquet lacus ut pharetra. Donec vitae mollis nisi. Etiam auctor pulvinar odio in venenatis. Morbi tincidunt, arcu eget vestibulum congue, nulla libero condimentum odio, quis tempus sem lectus vel quam. Cras fermentum scelerisque scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut in velit fringilla, porttitor neque nec, accumsan justo. Donec luctus pharetra augue. Vestibulum ac malesuada eros. Quisque viverra elit est, ut dignissim mi iaculis in. Morbi at sapien porttitor, accumsan lectus sit amet, blandit risus. Nulla aliquam arcu non lorem lobortis, in vestibulum libero interdum. Nunc malesuada et tellus ut elementum. Phasellus interdum mauris odio, sed egestas neque porta nec. Morbi commodo felis id semper cursus. Proin ante est, ornare id commodo id, condimentum a augue.

Ut nibh dui, sagittis at lorem ac, vehicula rutrum urna. Proin vel vehicula nisl. Integer blandit maximus nulla, eu suscipit odio iaculis non. Mauris quis magna a dui malesuada ultrices quis sed est. Sed mollis tincidunt mauris quis venenatis. Donec ullamcorper erat eu metus lacinia scelerisque. Aliquam erat volutpat.

Maecenas sollicitudin dui ut tortor mollis, sagittis iaculis mi auctor. Pellentesque a commodo ipsum, ac varius felis. Vivamus eu nunc a orci interdum gravida. Curabitur neque velit, dictum vel lacus eget, cursus pellentesque nisi. Etiam placerat felis et risus venenatis, id sollicitudin nibh suscipit. Integer id gravida mauris, quis lacinia neque. Sed ac sapien imperdiet, vestibulum dolor non, accumsan sapien. Integer est arcu, placerat ac elit quis, ornare tincidunt dui. Cras commodo eros vel enim iaculis, vitae fermentum lectus fermentum. Curabitur dapibus volutpat arcu nec dapibus. Suspendisse vestibulum, ipsum eget dictum cursus, ligula libero facilisis augue, a porttitor nisi lacus consectetur lacus. Suspendisse eleifend semper eros eu vestibulum. Fusce ultricies sem eu mauris facilisis, in tincidunt magna aliquam. Mauris et elementum erat. Nunc in finibus urna. Vestibulum ultrices ornare mi, vel dictum augue vulputate ac.

Nam auctor aliquam mi, et accumsan nisl. Phasellus tristique ex ac lorem tincidunt, sed vulputate nibh fermentum. Pellentesque eget orci est. Quisque et efficitur lorem. Nulla facilisi. Nulla vestibulum, nisi at convallis pulvinar, tortor odio hendrerit ex, et congue nunc est non felis. Nullam dui leo, viverra sed commodo nec, viverra non nulla. Nunc id iaculis orci, eu aliquam lectus. Fusce fringilla rhoncus ipsum, ac consectetur sem tempor vel. Nullam cursus facilisis sapien, quis sagittis nisi commodo eu. Maecenas auctor gravida lacus sed bibendum. Aliquam facilisis, lacus a iaculis malesuada, erat arcu consectetur urna, vel dapibus lacus mi non neque. Quisque sollicitudin ipsum sem, a lobortis tortor vehicula quis.

Quisque vel tincidunt erat. Vestibulum volutpat est at ante eleifend rhoncus. Aenean vel nunc eget urna fermentum vulputate at eu dolor. Duis gravida pretium mauris sed pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin euismod, risus sit amet pharetra faucibus, elit est accumsan orci, ut semper purus metus sit amet arcu. Phasellus et tempus nisl. Integer dignissim orci ut augue interdum placerat. Nullam pharetra, lacus non aliquet facilisis, lacus mi vehicula enim, ac facilisis sapien justo nec quam. Pellentesque gravida sagittis risus, et viverra lacus dapibus ut. Aliquam eu felis pellentesque, iaculis arcu et, consequat purus. Quisque congue tellus urna, sed finibus nibh venenatis a. Aenean mollis nisl sit amet urna euismod dignissim.
        </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis aliquet lacus ut pharetra. Donec vitae mollis nisi. Etiam auctor pulvinar odio in venenatis. Morbi tincidunt, arcu eget vestibulum congue, nulla libero condimentum odio, quis tempus sem lectus vel quam. Cras fermentum scelerisque scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut in velit fringilla, porttitor neque nec, accumsan justo. Donec luctus pharetra augue. Vestibulum ac malesuada eros. Quisque viverra elit est, ut dignissim mi iaculis in. Morbi at sapien porttitor, accumsan lectus sit amet, blandit risus. Nulla aliquam arcu non lorem lobortis, in vestibulum libero interdum. Nunc malesuada et tellus ut elementum. Phasellus interdum mauris odio, sed egestas neque porta nec. Morbi commodo felis id semper cursus. Proin ante est, ornare id commodo id, condimentum a augue.

Ut nibh dui, sagittis at lorem ac, vehicula rutrum urna. Proin vel vehicula nisl. Integer blandit maximus nulla, eu suscipit odio iaculis non. Mauris quis magna a dui malesuada ultrices quis sed est. Sed mollis tincidunt mauris quis venenatis. Donec ullamcorper erat eu metus lacinia scelerisque. Aliquam erat volutpat.

Maecenas sollicitudin dui ut tortor mollis, sagittis iaculis mi auctor. Pellentesque a commodo ipsum, ac varius felis. Vivamus eu nunc a orci interdum gravida. Curabitur neque velit, dictum vel lacus eget, cursus pellentesque nisi. Etiam placerat felis et risus venenatis, id sollicitudin nibh suscipit. Integer id gravida mauris, quis lacinia neque. Sed ac sapien imperdiet, vestibulum dolor non, accumsan sapien. Integer est arcu, placerat ac elit quis, ornare tincidunt dui. Cras commodo eros vel enim iaculis, vitae fermentum lectus fermentum. Curabitur dapibus volutpat arcu nec dapibus. Suspendisse vestibulum, ipsum eget dictum cursus, ligula libero facilisis augue, a porttitor nisi lacus consectetur lacus. Suspendisse eleifend semper eros eu vestibulum. Fusce ultricies sem eu mauris facilisis, in tincidunt magna aliquam. Mauris et elementum erat. Nunc in finibus urna. Vestibulum ultrices ornare mi, vel dictum augue vulputate ac.

Nam auctor aliquam mi, et accumsan nisl. Phasellus tristique ex ac lorem tincidunt, sed vulputate nibh fermentum. Pellentesque eget orci est. Quisque et efficitur lorem. Nulla facilisi. Nulla vestibulum, nisi at convallis pulvinar, tortor odio hendrerit ex, et congue nunc est non felis. Nullam dui leo, viverra sed commodo nec, viverra non nulla. Nunc id iaculis orci, eu aliquam lectus. Fusce fringilla rhoncus ipsum, ac consectetur sem tempor vel. Nullam cursus facilisis sapien, quis sagittis nisi commodo eu. Maecenas auctor gravida lacus sed bibendum. Aliquam facilisis, lacus a iaculis malesuada, erat arcu consectetur urna, vel dapibus lacus mi non neque. Quisque sollicitudin ipsum sem, a lobortis tortor vehicula quis.

Quisque vel tincidunt erat. Vestibulum volutpat est at ante eleifend rhoncus. Aenean vel nunc eget urna fermentum vulputate at eu dolor. Duis gravida pretium mauris sed pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin euismod, risus sit amet pharetra faucibus, elit est accumsan orci, ut semper purus metus sit amet arcu. Phasellus et tempus nisl. Integer dignissim orci ut augue interdum placerat. Nullam pharetra, lacus non aliquet facilisis, lacus mi vehicula enim, ac facilisis sapien justo nec quam. Pellentesque gravida sagittis risus, et viverra lacus dapibus ut. Aliquam eu felis pellentesque, iaculis arcu et, consequat purus. Quisque congue tellus urna, sed finibus nibh venenatis a. Aenean mollis nisl sit amet urna euismod dignissim.
        </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis aliquet lacus ut pharetra. Donec vitae mollis nisi. Etiam auctor pulvinar odio in venenatis. Morbi tincidunt, arcu eget vestibulum congue, nulla libero condimentum odio, quis tempus sem lectus vel quam. Cras fermentum scelerisque scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut in velit fringilla, porttitor neque nec, accumsan justo. Donec luctus pharetra augue. Vestibulum ac malesuada eros. Quisque viverra elit est, ut dignissim mi iaculis in. Morbi at sapien porttitor, accumsan lectus sit amet, blandit risus. Nulla aliquam arcu non lorem lobortis, in vestibulum libero interdum. Nunc malesuada et tellus ut elementum. Phasellus interdum mauris odio, sed egestas neque porta nec. Morbi commodo felis id semper cursus. Proin ante est, ornare id commodo id, condimentum a augue.

Ut nibh dui, sagittis at lorem ac, vehicula rutrum urna. Proin vel vehicula nisl. Integer blandit maximus nulla, eu suscipit odio iaculis non. Mauris quis magna a dui malesuada ultrices quis sed est. Sed mollis tincidunt mauris quis venenatis. Donec ullamcorper erat eu metus lacinia scelerisque. Aliquam erat volutpat.

Maecenas sollicitudin dui ut tortor mollis, sagittis iaculis mi auctor. Pellentesque a commodo ipsum, ac varius felis. Vivamus eu nunc a orci interdum gravida. Curabitur neque velit, dictum vel lacus eget, cursus pellentesque nisi. Etiam placerat felis et risus venenatis, id sollicitudin nibh suscipit. Integer id gravida mauris, quis lacinia neque. Sed ac sapien imperdiet, vestibulum dolor non, accumsan sapien. Integer est arcu, placerat ac elit quis, ornare tincidunt dui. Cras commodo eros vel enim iaculis, vitae fermentum lectus fermentum. Curabitur dapibus volutpat arcu nec dapibus. Suspendisse vestibulum, ipsum eget dictum cursus, ligula libero facilisis augue, a porttitor nisi lacus consectetur lacus. Suspendisse eleifend semper eros eu vestibulum. Fusce ultricies sem eu mauris facilisis, in tincidunt magna aliquam. Mauris et elementum erat. Nunc in finibus urna. Vestibulum ultrices ornare mi, vel dictum augue vulputate ac.

Nam auctor aliquam mi, et accumsan nisl. Phasellus tristique ex ac lorem tincidunt, sed vulputate nibh fermentum. Pellentesque eget orci est. Quisque et efficitur lorem. Nulla facilisi. Nulla vestibulum, nisi at convallis pulvinar, tortor odio hendrerit ex, et congue nunc est non felis. Nullam dui leo, viverra sed commodo nec, viverra non nulla. Nunc id iaculis orci, eu aliquam lectus. Fusce fringilla rhoncus ipsum, ac consectetur sem tempor vel. Nullam cursus facilisis sapien, quis sagittis nisi commodo eu. Maecenas auctor gravida lacus sed bibendum. Aliquam facilisis, lacus a iaculis malesuada, erat arcu consectetur urna, vel dapibus lacus mi non neque. Quisque sollicitudin ipsum sem, a lobortis tortor vehicula quis.

Quisque vel tincidunt erat. Vestibulum volutpat est at ante eleifend rhoncus. Aenean vel nunc eget urna fermentum vulputate at eu dolor. Duis gravida pretium mauris sed pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin euismod, risus sit amet pharetra faucibus, elit est accumsan orci, ut semper purus metus sit amet arcu. Phasellus et tempus nisl. Integer dignissim orci ut augue interdum placerat. Nullam pharetra, lacus non aliquet facilisis, lacus mi vehicula enim, ac facilisis sapien justo nec quam. Pellentesque gravida sagittis risus, et viverra lacus dapibus ut. Aliquam eu felis pellentesque, iaculis arcu et, consequat purus. Quisque congue tellus urna, sed finibus nibh venenatis a. Aenean mollis nisl sit amet urna euismod dignissim.
        </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis aliquet lacus ut pharetra. Donec vitae mollis nisi. Etiam auctor pulvinar odio in venenatis. Morbi tincidunt, arcu eget vestibulum congue, nulla libero condimentum odio, quis tempus sem lectus vel quam. Cras fermentum scelerisque scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut in velit fringilla, porttitor neque nec, accumsan justo. Donec luctus pharetra augue. Vestibulum ac malesuada eros. Quisque viverra elit est, ut dignissim mi iaculis in. Morbi at sapien porttitor, accumsan lectus sit amet, blandit risus. Nulla aliquam arcu non lorem lobortis, in vestibulum libero interdum. Nunc malesuada et tellus ut elementum. Phasellus interdum mauris odio, sed egestas neque porta nec. Morbi commodo felis id semper cursus. Proin ante est, ornare id commodo id, condimentum a augue.

Ut nibh dui, sagittis at lorem ac, vehicula rutrum urna. Proin vel vehicula nisl. Integer blandit maximus nulla, eu suscipit odio iaculis non. Mauris quis magna a dui malesuada ultrices quis sed est. Sed mollis tincidunt mauris quis venenatis. Donec ullamcorper erat eu metus lacinia scelerisque. Aliquam erat volutpat.

Maecenas sollicitudin dui ut tortor mollis, sagittis iaculis mi auctor. Pellentesque a commodo ipsum, ac varius felis. Vivamus eu nunc a orci interdum gravida. Curabitur neque velit, dictum vel lacus eget, cursus pellentesque nisi. Etiam placerat felis et risus venenatis, id sollicitudin nibh suscipit. Integer id gravida mauris, quis lacinia neque. Sed ac sapien imperdiet, vestibulum dolor non, accumsan sapien. Integer est arcu, placerat ac elit quis, ornare tincidunt dui. Cras commodo eros vel enim iaculis, vitae fermentum lectus fermentum. Curabitur dapibus volutpat arcu nec dapibus. Suspendisse vestibulum, ipsum eget dictum cursus, ligula libero facilisis augue, a porttitor nisi lacus consectetur lacus. Suspendisse eleifend semper eros eu vestibulum. Fusce ultricies sem eu mauris facilisis, in tincidunt magna aliquam. Mauris et elementum erat. Nunc in finibus urna. Vestibulum ultrices ornare mi, vel dictum augue vulputate ac.

Nam auctor aliquam mi, et accumsan nisl. Phasellus tristique ex ac lorem tincidunt, sed vulputate nibh fermentum. Pellentesque eget orci est. Quisque et efficitur lorem. Nulla facilisi. Nulla vestibulum, nisi at convallis pulvinar, tortor odio hendrerit ex, et congue nunc est non felis. Nullam dui leo, viverra sed commodo nec, viverra non nulla. Nunc id iaculis orci, eu aliquam lectus. Fusce fringilla rhoncus ipsum, ac consectetur sem tempor vel. Nullam cursus facilisis sapien, quis sagittis nisi commodo eu. Maecenas auctor gravida lacus sed bibendum. Aliquam facilisis, lacus a iaculis malesuada, erat arcu consectetur urna, vel dapibus lacus mi non neque. Quisque sollicitudin ipsum sem, a lobortis tortor vehicula quis.

Quisque vel tincidunt erat. Vestibulum volutpat est at ante eleifend rhoncus. Aenean vel nunc eget urna fermentum vulputate at eu dolor. Duis gravida pretium mauris sed pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin euismod, risus sit amet pharetra faucibus, elit est accumsan orci, ut semper purus metus sit amet arcu. Phasellus et tempus nisl. Integer dignissim orci ut augue interdum placerat. Nullam pharetra, lacus non aliquet facilisis, lacus mi vehicula enim, ac facilisis sapien justo nec quam. Pellentesque gravida sagittis risus, et viverra lacus dapibus ut. Aliquam eu felis pellentesque, iaculis arcu et, consequat purus. Quisque congue tellus urna, sed finibus nibh venenatis a. Aenean mollis nisl sit amet urna euismod dignissim.
        </p>
    </div>
       
    )
}